# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f80cda095d68e74adb54c9c88ccab30d7d328495b9d864a4ec3202dc6d84d9809c70769dbb26111d2a599e29cf571689db79fb0b6e5869eaf561c9a47aece9df

test:
  secret_key_base: f624a8e721518e4fd63e980ab4d13a9592f1fb14c02eeb3f859286dd3fe308f6a8224e8e8a83769451f612d3c2468805e97566bcf082a5417ff1471cf1033336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
